# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tumor-prediction-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: tumor-prediction-app
    

