name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run Tests
      - name: Run Tests
        run: |
          nose2

      # Step 5: Lint with Flake8
      - name: Lint with Flake8
        run: |
          flake8

      # Step 6: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t tumor-prediction:${{ github.sha }} .

      # Step 7: Install AWS CLI
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      # Step 8: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 9: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      # Step 10: Push Docker image to ECR
      - name: Push Docker image to ECR
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          docker tag tumor-prediction:${{ github.sha }} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/tumor-prediction-repo:${{ github.sha }}
          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/tumor-prediction-repo:${{ github.sha }}

      # Step 11: Check if EKS cluster exists
      - name: Check if EKS cluster exists
        id: check_cluster
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
        run: |
          CLUSTER_STATUS=$(aws eks describe-cluster --name $CLUSTER_NAME  --region $AWS_REGION --query 'cluster.status' --output text 2>/dev/null || echo 'None')
          echo "cluster_status=$CLUSTER_STATUS" >> $GITHUB_OUTPUT

      # Step 12: Fail if cluster does not exist
      - name: Fail if cluster does not exist
        if: steps.check_cluster.outputs.cluster_status == 'None'
        run: |
          echo "EKS cluster does not exist. Exiting."
          exit 1

      # Step 13: Set Up kubectl
      - name: Set Up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.0'

      # Step 14: Update kubeconfig for EKS cluster
      - name: Update kubeconfig for EKS cluster
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
        run: |
          aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      # Step 15: Test kubectl connection
      - name: Test kubectl connection
        run: |
          kubectl get nodes

      # Step 16: Test for existing service and apply
      - name: Test and Deploy service
        env: 
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          if ! kubectl get service tumor-prediction-service -n default; then
            echo "Service does not exist. Creating service..."
            kubectl apply -f tumor-prediction/terraform/k8s-resources/kubernetes/service.yaml

          else 
            echo "Service already exists. No changes made."
          fi

      # Step 17: Test for existing deployment and apply
      - name: Test and Deploy deployment
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          IMAGE_TAG: ${{ github.sha }}
          DEPLOYMENT_NAME: tumor-prediction-deployment
        run: |
          if kubectl get deployment ${DEPLOYMENT_NAME} -n default; then
            echo "Deployment exists. Peforming rolling restart."
            kubectl rollout restart deployment/${DEPLOYMENT_NAME}
          else
            echo "No existing deployment. Creating new Deployment"
            envsubst < tumor-prediction/terraform/k8s-resources/kubernetes/deployment.yaml | kubectl apply -f -
          fi